### Start a New Game
POST http://localhost:7164/ChessGame/start
Content-Type: application/json
Accept: application/json

{
  "PlayerWhiteName": "Alice",
  "PlayerBlackName": "Bob"
}

### Start a new game
POST http://localhost:7164/ChessGame/start
Content-Type: application/json
Accept: application/json

{
  "PlayerWhiteName": "Brock",
  "PlayerBlackName": "Lesnar"
}

### Make a Move in an Existing Game
POST http://localhost:7164/ChessGame/move
Content-Type: application/json
Accept: application/json

{
  "GameId": "f5b5582f-252d-44e4-9d23-6de31e44cef8",
  "Move": "P-e2-e3",
  "PlayerName": "Alice"
}

### Make a Move in an Existing Game
POST http://localhost:7164/ChessGame/move
Content-Type: application/json
Accept: application/json

{
  "GameId": "f5b5582f-252d-44e4-9d23-6de31e44cef8",
  "Move": "P-e7-e6",
  "PlayerName": "Bob"
}

### Make a Move in an Existing Game
POST http://localhost:7164/ChessGame/move
Content-Type: application/json
Accept: application/json

{
  "GameId": "a0e16274-d69f-4947-b36a-f3dd2501b9b2",
  "Move": "K-g1-f3",
  "PlayerName": "Bob"
}

### Get Active Games
GET http://localhost:7164/ChessGame/games
Accept: application/json

### Get board state of a game
GET http://localhost:7164/ChessGame/board?gameId=8f822242-f692-48e3-b244-3292c68fc076