### Start a New Game
POST http://localhost:7164/ChessGame/start
Content-Type: application/json
Accept: application/json

{
  "PlayerWhiteName": "Alice",
  "PlayerBlackName": "Bob"
}

### Start a new game
POST http://localhost:7164/ChessGame/start
Content-Type: application/json
Accept: application/json

{
  "PlayerWhiteName": "Brock",
  "PlayerBlackName": "Lesnar"
}

### Make a Move in an Existing Game
POST http://localhost:7164/ChessGame/move
Content-Type: application/json
Accept: application/json

{
  "GameId": "64d2747b-3efa-4fa0-b0a2-8f413d48c466",
  "Move": "P-e2-e3",
  "PlayerName": "Alice"
}

### Get Active Games
GET http://localhost:7164/ChessGame/games
Accept: application/json

### Get board state of a game
GET http://localhost:7164/ChessGame/board?gameId=64d2747b-3efa-4fa0-b0a2-8f413d48c466